# Generated by Django 4.2.20 on 2025-03-21 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admitionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.CharField(blank=True, max_length=20)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('nationality', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('mother_tongue', models.CharField(blank=True, max_length=50)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('caste', models.CharField(blank=True, max_length=50)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('id_mark', models.TextField(blank=True)),
                ('student_photo', models.ImageField(blank=True, upload_to='student_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('father_job', models.CharField(blank=True, max_length=100)),
                ('father_education', models.CharField(blank=True, max_length=100)),
                ('father_mobile', models.CharField(max_length=10)),
                ('father_email', models.EmailField(blank=True, max_length=254)),
                ('father_place', models.CharField(blank=True, max_length=100)),
                ('father_photo', models.ImageField(blank=True, upload_to='parent_photos/')),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_job', models.CharField(blank=True, max_length=100)),
                ('mother_education', models.CharField(blank=True, max_length=100)),
                ('mother_mobile', models.CharField(max_length=10)),
                ('mother_email', models.EmailField(blank=True, max_length=254)),
                ('mother_place', models.CharField(blank=True, max_length=100)),
                ('mother_photo', models.ImageField(blank=True, upload_to='parent_photos/')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admitionapp.student')),
            ],
        ),
    ]
