# Generated by Django 4.2.20 on 2025-03-24 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admitionapp', '0008_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admitionapp.standard', verbose_name='Class/Standard'),
        ),
    ]
