# Generated by Django 4.2.20 on 2025-03-24 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admitionapp', '0010_alter_student_standard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Standard',
        ),
    ]
