# Generated by Django 4.2.20 on 2025-03-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admitionapp', '0014_alter_student_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
