# Generated by Django 4.2.20 on 2025-03-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admitionapp', '0015_standard_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='academic_year',
            field=models.CharField(default=2, help_text='e.g., 2024-2025', max_length=20),
            preserve_default=False,
        ),
    ]
