# Generated by Django 4.2.20 on 2025-03-28 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admitionapp', '0019_alter_student_approved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='approved_by',
        ),
    ]
