# Generated by Django 4.2.2 on 2025-03-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admitionapp', '0020_remove_student_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancel', 'Cancel')], default='pending', max_length=10),
        ),
    ]
