# Generated by Django 4.2.20 on 2025-04-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admitionapp', '0021_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='standard',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Standard',
        ),
    ]
