# Generated by Django 4.2.20 on 2025-04-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admitionapp', '0023_standard_alter_student_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='standard',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='Standard',
        ),
    ]
