# Generated by Django 4.2.20 on 2025-04-07 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admitionapp', '0025_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admitionapp.standard'),
        ),
    ]
