# Generated by Django 4.2.20 on 2025-04-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admitionapp', '0026_alter_student_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='standard',
            field=models.CharField(blank=True, default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Standard',
        ),
    ]
