# Generated by Django 4.2.20 on 2025-04-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admitionapp', '0027_alter_student_standard_delete_standard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Standard Name')),
                ('value', models.CharField(max_length=50, verbose_name='Standard Value')),
            ],
        ),
    ]
