# Generated by Django 4.2.20 on 2025-04-08 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admitionapp', '0029_alter_student_standard'),
    ]

    operations = [
    ]
